--- 

files: 
  - source: /
    destination: /home/ec2-user/web
    
hooks: 
  BeforeInstall: 
    - 
      location: Scripts/b4install.sh
      runas: root
      timeout: 300

os: linux
permissions: 
  - 
    pattern: "**"
    object: /
    type: 
      - directory
      - file
version: 0.0
