--- 
files: 
  - 
    destination: /home/ec2-user/node
    source: /
hooks: 
  AfterInstall: 
    - 
      commands:
        - echo done
      runas: ec2-user
      timeout: 600
  ApplicationStart: 
    - 
      commands: 
        - npm start
      runas: ec2-user
      timeout: 120
  ApplicationStop: 
    - 
      commands: 
        - npm stop
      runas: ec2-user
      timeout: 120
  BeforeInstall: 
    - 
      location: install.sh
      runas: root
      timeout: 300
  ValidateService: 
    - 
      commands: 
        - npm start
      runas: ec2-user
      timeout: 60
os: linux
permissions: 
  - 
    group: ec2-user
    object: /home/ec2-user
    owner: ec2-user
    type: 
      - directory
      - file
version: 0.0
