--- 

files: 
  - source: /
    destination: /home/ec2-user/web
    
hooks: 
  AfterInstall: 
    - 
      location: Scripts/post_install.sh
      runas: root
      timeout: 600
  ApplicationStart: 
    - 
      location: Scripts/run.sh
      runas: root
      
  ApplicationStop: 
    - 
      location: Scripts/stop.sh
      runas: root
      timeout: 120
  BeforeInstall: 
    - 
      location: Scripts/b4install.sh
      runas: root
      timeout: 300
  ValidateService: 
    - 
      location: Scripts/validation.sh
      runas: ec2-user
      timeout: 60
os: linux
permissions: 
  - 
    group: ec2-user
    object: /home/ec2-user
    owner: ec2-user
    type: 
      - directory
      - file
version: 0.0
