version: 0.2

os: 
  linux
files:
- source: 
  /
 destination: 
  /home/ec2-user/my-app

permissions:
  - object: 
    /
   pattern: 
    "**"
   owner: 
    ec2-user
   group: e
    c2-user

hooks:
ApplicationStop:
   - location: bin/app-stop
     timeout: 10
     runas: ec2-user

AfterInstall:
   - location: bin/install-pkgs
     timeout: 1200
     runas: ec2-user

ApplicationStart:
   - location: bin/app-start
     timeout: 60
     runas: ec2-user

ValidateService:
   - location: bin/app-validate
     timeout: 10
     runas: ec2-user