--- 
files: 
  - 
    destination: /home/ec2-user/node
    source: /AWSTestRepo/Scripts
hooks: 
  AfterInstall: 
    - 
      commands: post_install.sh
      runas: ec2-user
      timeout: 600
  ApplicationStart: 
    - 
      location: /home/ec2-user/node/run.sh
      runas: ec2-user
      timeout: 120
  ApplicationStop: 
    - 
      location: /home/ec2-user/node/stop.sh
      runas: ec2-user
      timeout: 120
  BeforeInstall: 
    - 
      location: /home/ec2-user/node/install.sh
      runas: root
      timeout: 300
  ValidateService: 
    - 
      location: /home/ec2-user/node/validation.sh
      runas: ec2-user
      timeout: 60
os: linux
permissions: 
  - 
    group: ec2-user
    object: /home/ec2-user
    owner: ec2-user
    type: 
      - directory
      - file
version: 0.0
